public class dml {

    public static void mymethod(){
        List<Account> accList = new List<Account>();
        for(integer i=11;i<12;i++){
            Account acc= new Account();
            acc.Name='database';
            acc.AnnualRevenue=4400000;
			acc.Rating='warm';
             accList.add(acc);
            
          //  for(integer i=11;i<12;i++){ 
            
            
        }
    }
}